language: cpp
sudo: required

compiler:
  - clang
  - gcc

install:
  - wget --quiet -O - https://raw.githubusercontent.com/r-lyeh/depot/master/travis.pre.sh   | bash -x

before_script:
  - mkdir build
  - cd build
  - pwd
  - cmake 

script:
  - pwd
  - make

